workflows:
  testwf1:
    name: Test workflow 1
    instance_type: mac_mini
    max_build_duration: 40
    environment:
      vars:
        XCODE_PROJECT: "nativetestapp.xcodeproj"  # PUT YOUR WORKSPACE NAME HERE
        XCODE_SCHEME: "nativetestapp" # PUT THE NAME OF YOUR SCHEME HERE
        # iOS automatic code signing
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(Z0FBQUFBQmdKVWdUYWZUZmxIa2kxUHYwdGlsVjNRbVk3WDZvZHhjZGxVU3YwQVZ4TjlQSTA0cXY1R0JCN1JRaGFBYTFPT2FRX09zdzdCQXRTUngxbXRSLUtPODB3ZU84MkN4Y2w4OXRxZFdEdktJMVBQbGpUbkdkZ21hUDJ6VnRGNFRmNGwyU1VCV0U=)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Z0FBQUFBQmdKVWZxYWgxckxzTGQ1SHpwN3c1Z3JkZUVvWWNzWjlzZTh1MVhWMGxrekFXYXl6UjZrVXozdzhBODZpdUZma2daNmhuOTZfX1dlZ3JvSTNvR1NkSElHZUxzUXc9PQ==)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdKVXhVeXNUSDlvZkNDaVBaal84MjBGa1pJbHNWVlNCVk1FSWxsZV9FSlk5cm5fRUpacnJ5ZHVYZnhjS1FiTUVqdVpSWVMxd3Byem5TeG5aNk95bjdmVmptdlV5WlV2TGVISW1YRzBrcF9CcTlXVFdlZ2hfQmRGekpzMEdJVDkySkRobFBZY3dwc0NWcERFdk9KSE5WbGd1Z2VKZHJnb2trT05oalBJT2xRaWtILVl2aXY4NzBPVFlHWGJEOEFxUnI5SF81VHgtM2kyd0thZ0w2WHcxVVczd05fVWtwWjR3dkhWTzZObElfQzFOV25hNEdkRUt6dVp1QThPVl9YZVpvNkd4QWlWN1UyMVpUZzU5M0NJSVBybzV3X3FBdXFmSjRDaTRBQ2JzZzg5NEphVDZBcHUxbnN0bE51c0ozYkdMeFc5ZTA0OXNybXNEQXVTeVFqVUp0UlJLa0xyX1ctWU1pa1RHaE1sSGVVOGZPYmFzQ1FyWFMzOVYzd0JWSV9TQkFnZmJxZzdsZE40U1lESmdBeXJUQTM0Sm1nVzBCSmFLZEdkM0lrZ2JHbzhUaUxybz0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdKVXJabWtfYjZ6R05rakU1UkZzejZDaTBxTWNpd0hWQ0UyajlHcy0wekxfaHVud2w4VFg3ZXdDU0UxZjE4TU1TeUdvcU1ZQWJjNVBSNFB1MlVscjdIWHQzSVNQVHU4VkRSLVZ1bThRcnZXZlprZFA5UXgxdm92TlFkNHJ3N3pVQVRBSkw5MVpxQW5SS2dsNjJ5RUt3REQtSGFVSXlEdTFoRkpsWWtXdGtNUnhjSi1laERlb2RmaWpQVVIwYVEwYldlcXZZbFBHSUJsWnVKdHU4SVh5VU1xQV9SYmhJX0RWQ2dQVno0eWxkQjFScnZFVWRHYlA4MjAzMEZoMEhjTkMyOWxTVEtNNktvMUNTek5fR2dtTmtmWTZjN3plN2dvRURzTEtLTHBwbmk5cGRQbmJPNWtIdVpuYll3Z3dVZzAtdnpzd0ltU0xCSHBNclpidFFyeGwxbnB6UndsVllDUFZjQzZ6eHpEd2ZqOWY3dzJjNjFfWTBFZEtKNkVuSkxCclhaQWN3Yk43UUpmUUVFX0xpcnR4QkJVLTBWMWhLVVhvNUJFVjlPMWZ4QW5WQ0JaemdqRlpKN1FmQlhBaVF4Um1Kdm1MMGRsRkN0M1JjOFo3eVdINjdlWnd2Mk9VTGdHZzNrZ0pscDdKYjhaY2VqQXBPQ2duOHNzZHIyUXY3ZWtUeXZYaE5tRzZ5dGR2MlQ2bzFnMUVFd1lqVmhtUnlOT0VuMGRnOS1oemNyMm12U1ViY1RjSUVPNWpubzB2RnJCLTJqUTJ3Z3NOdkpUN08xZl9HQjkzSDV1bTdLMGFqOWhYUmJJY2ZHZGhBUTZETjNuekkxbkpKNy1ReHpFVGdiMzhoT2wtN2NPS250dUxTWXJUMWVlajdJMDAxc01RZFFueXdoWWhNUVZpdXM0U2JxMkFnY0NiU05xeDBQNEYyczdZRVRYQU15VmV0WGtXZEVwTTZ5X0dmVUNISl9ULW5JbUU0bTkwZzNnTU9MRTQ4NUUyeDhEZEcwRzJ1YUxRVkhWVlhoTmdYZFlCSGM4VVhXQW5aMHQ3SXpVbjd4NGNrWDR5Rnp1THduazhoNTJFQWV0ZkYzdE85Ynl2RmNsdjlVTTdpT19lSlB1Mk9TWWM5cXEyYk91alNwQzh5c2ZkU3EzU0trd0VacXlJYWtYZHlPNFFLWk90aUFQM0dPbG95ZVVVUzVucTdINnJrMUs5ZTNHOUNJNWZ4MThPVU5MampKeS1hYXpEYm1DOHpjS0RoWWl4NlNSaC1EaVZVTWc3UG8yaHZSUno4dE4tbFJoS0I4b054ckxGa29NbW9LdVBHRGlyZXctY3lESDJwXzVxVk5famdLSTRLQ0hqNGkyYnk1TG84Smlxenl5bDhnUE5xeWxyNWxyOHAzc0VSMTFIaklYTklhNUVxblFzVmk3SDluYXNmcWhkSUkxTVV0b2tiUlplbnlsSTQxdlYwQlo4QXE4ZFdWVnFKZ2E1UndIOFdGY1RrclotcXlJazA2WkxCcEpHU3ZyS1FhN0FNWmpEZ0J2RXhld3BEbUtFU0NVYlJURFFwb1cwcjhESlYxb0dTTFNGT0RfZXZfVHp6cmxhWUM4bUVxYjVuSHN2U3VndHVkNmJDVExSSk4zc2JoWlEtMWNmc3laUHB3SUliOEZ3VFhNdkJsbTBjdHU1ZGlrLWdXdjMxZF9qSml0WjBlSlF3UEF5emJKejdMc3JkMnJualFlNHRCQWJJTlo5R0xQcTA3V0kzdEJldUhfSkREOVRIYnlxcTRqdVIxN0xSY3VDRTE2MlNBb3BnaEVhX1V3S1VKS2lfdExYTjhjcU1aczlMbXdDRDl0WllFb1kzZG1lMHpqUlJwc1E1NGI4VGUtTzRrUGItblNWN2h1eWRWZVNWWHFfQm9BdTBRSm1DVXhlRVRGYVkwMWY5Snp4bV9tVmYyMGlmM09GYm1Tc3FCSTVEOXVoQnVHNFhHVVhlVzhnZUdjU0o1MHpLM2lVTmN5N05XVkRGR2tCWUR2MEZJbXQwQ3NSeGFaTXQwWTVGZFNvaE1SU2ZwMkQyRktOSTI4QWRjc3lXQndHWUhLZEVERGEySkNwTWx1bnlEa3gyUi1pVktLTWdNQmR0Y0V0LThydGJPZDNfVzB1OFFvRmxvVGZ6dFdsVDhvOHNFQ3dtZlVsbUNXSlM2Nmp1VndoM3lJR0dGZ2xnOVNUWHFIazNtbmZ0WC1mUm5kNGpDSmc4SnFDZTRLdGhaZDNTQUxpa1YxRWh0LXFEX2sxYllCUnU3eFFSdEpiZjlRUl9hSG14ak5pcS1HX0JlVUprcy1jQm5IaUpTTGx2cy10RERQY2FEVzlXbU10bFZEanVER29vWmJJZFBFTFQ5SlZDUTZsY3RFdGlSOFVxbDJrcENDcGtRd1BmLW1rSllrZmZpNjcwclJxQ1hnSWdYUVBPRHBNQTBhMnF3Um1HSF81OGpXQlBHZl9Qei11ZVJlcHFYYlYySV9MZ1BnUUJLN1N3eUhiSnlVNkRuRXVZQlM4NkZ0SzR0bmVTeUc0RTl5R0RRSS1XSUt2WTd1dm0taDZxdzdoR1lTQ0Rka0VJbml6Q0ktbXRKOUd6VE9vX0dMRkQzaGVtOHM4SUpWdkRKZWU5MDA3ZDRLR0lpVENOaVJ2QmVIVGVaZGNwR0Q4YjNVZEx0Z3ZRdWtGc0pxM3EwSld2SUVQZ1JNa0w2UVNUb2ZOUXBwR1YydVNORFRrMG5VQnhPLThSMThsWHNERjhOaXFFMXJwNTBUZnNYa1JLNmJkZnd1VTUzLVljRUtKM2VjbEU5OXE1QUdkdlRXWTlzaUpTZm0yYjNtaWJJcEFhMmtaUVR2UzRtVkpZYnFHV05NZXVFQ0ZubU9fOEJTckFwaXpuZFRpVFZ5clVIVjc1bFNaRzA4Vmg4YUF1LV9DWXlVS1oxOENiZzAxcnpMeEJ4TDdkVE0tUDFTUGRPbXhud0hMMDVTbmt2WmVNUWJaX0tXYndjV050c2U2R0VEQzFFUWxIdnlZdHUwbXVid0pFUVdvWWVxdHdWZ3dTbWZDaUNuZHVGNE1WVXYtQUxtOGFXTmJp)
        # Other stuff
      xcode: latest
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'labidas'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "io.codemagic.app" \
            --type IOS_APP_DEVELOPMENT \
            --create    
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build versioning
        script: | 
          #!/bin/sh
          set -e
          set -x
          cd $FCI_BUILD_DIR/ios
          agvtool new-version -all $BUILD_NUMBER
          agvtool new-marketing-version 1.0.3
      - name: Build ipa for distribution
        script: xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
